### ISSUE TITLE
Can't find object_detection.utils

### ISSUE THREAD

**Issue by kwan96** [soonhahwang/Mobilenet-SSD-to-detect-Licence-Plate#1]
Nice work! but it seems the object_detection python file didn't upload.

**Comment by soonhahwang** [comment]
Hi @kwan96,
hmm I didn't upload object_detection/utils in my github because it's all included in the tensorflow.
More specifically, you will be able to find it here: https://github.com/tensorflow/models/tree/master/research/object_detection/utils

**Comment by kwan96** [comment]
Oh, ok, thanks for your reply.
